# Generated by Django 3.2.5 on 2021-07-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
                ('personnel', models.IntegerField()),
                ('title', models.TextField()),
                ('meetingdate', models.DateTimeField(null=True)),
            ],
        ),
    ]
